#!/bin/bash

# Level 13: Backup Script with Rotation

# Mission: Create a script that backs up a directory to a specified location and keeps only the last 5 backups.

directory="$1"
backup_directory="$2"
mkdir -p $backup_directory
timestamp=$(date +"%m-%d-%Y_%H:%M:%S")
backup_name=${directory}_backup_$timestamp.tar.gz
tar -czf "$backup_name" "$directory" 

mv "$backup_name" $backup_directory

echo "Created backup: $backup_name and moved to $backup_directory"

cd $backup_directory

rm -r $(ls -t | tail -n +6)
