#!/bin/bash

# Level 10: Boss Battle 2 - Intermediate Scripting

# Mission: Write a script that:

# 1. Creates a directory called Arena_Boss.
# 2. Creates 5 text files inside the directory, named file1.txt to file5.txt.
# 3. Generates a random number of lines (between 10 and 20) in each file.
# 4. Sorts these files by their size and displays the list.
# 5. Checks if any of the files contain the word 'Victory', and if found, moves the file to a directory called Victory_Archive.

mkdir -p Arena_Boss
cd Arena_Boss
touch {file1,file2,file3,file4,file5}.txt
for n in $(seq 1 5); do
    random_number=$((RANDOM % 11 + 10))
    for lines in $(seq 1 $random_number); do
        echo "line: $lines" >> file$n.txt
    done
done
ls -lS | awk '{ print $5, $9 }'
mkdir -p Victory_Archive
Search_term=$(grep -lr "Victory")
if [[ -n "$Search_term" ]]; then
    mv $Search_term Victory_Archive
fi
